name: CI

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
      - "__tests__/**"
      - "eslint.config.mjs"
      - "jest.config.mjs"
      - "tsconfig.json"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/ci.yml"
      - "src/**"
      - "__tests__/**"
      - "eslint.config.mjs"
      - "jest.config.mjs"
      - "tsconfig.json"

env:
  HUSKY: 0

jobs:
  lint:
    name: Lint Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.4"

      - name: Enable Corepack
        run: corepack enable

      - name: Install Packages
        run: yarn install --immutable

      - name: Running Lint
        run: yarn lint

  test:
    name: Test Files
    strategy:
      matrix:
        node: ["22.4", 20.x, "20.9", 18.x, "18.18"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install Packages
        run: yarn install --immutable

      - name: Running Test
        run: yarn test
